name: Run Selenium Tests with Maven and Generate Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install Chrome and ChromeDriver
      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      # Step 5: Set up Maven
      - name: Set up Maven
        run: mvn --version

      # Step 6: Run Maven tests
      - name: Run Tests
        run: mvn clean test

      # Step 7: Generate Allure Report
      - name: Generate Allure Report
        run: |
          mkdir -p allure-results
          mv target/allure-results/* allure-results/
          allure generate allure-results --clean --output allure-report

      # Step 8: Upload Allure Report as an artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      # Step 9: Serve Allure Report (Optional)
      - name: Deploy Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
